//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int idUsuario { get; set; }
        public string nick { get; set; }
        public string correo { get; set; }
        public string clave { get; set; }
        public int edad { get; set; }
        public double peso { get; set; }
        public double altura { get; set; }
        public System.DateTime fechaRegistro { get; set; }
    
        public virtual Calendario Calendario { get; set; }
    }
}
