//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessDaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class receta
    {
        public int idRecetas { get; set; }
        public int idUsuario { get; set; }
        public int idCalendario { get; set; }
        public int idRegistros { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public float calorias { get; set; }
        public float proteinas { get; set; }
        public float grasas { get; set; }
        public float gramos { get; set; }
        public float carboidratos { get; set; }
        public int calificacion { get; set; }
    
        public virtual calendario calendario { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
