//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessDaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.articuloes = new HashSet<articulo>();
            this.calendarios = new HashSet<calendario>();
            this.recetas = new HashSet<receta>();
        }
    
        public int idUsuario { get; set; }
        public string nick { get; set; }
        public string correo { get; set; }
        public string contrasena { get; set; }
        public int edad { get; set; }
        public float peso { get; set; }
        public float altura { get; set; }
        public System.DateTime fecha_de_registro { get; set; }
    
        public virtual ICollection<articulo> articuloes { get; set; }
        public virtual ICollection<calendario> calendarios { get; set; }
        public virtual ICollection<receta> recetas { get; set; }
    }
}
